CC = nvcc
#CC = gcc
OPT = -qopenmp -O3 -g -mkl -heap-arrays -ip -ipo -parallel -std=c++11

SRCS = cuda_dpposeEstimation.cu 

LIB = 

EXE = dpestimation.exe

run: all
	./dpestimation.exe

all: cuda_dpposeEstimation.cu
	$(CC) $(OPT) $(LIB) $(SRCS) -o $(EXE)

clean: 
	rm ./dpestimation.exe    
